<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="10.0.1" />
    <PackageReference Include="Mono.Cecil" Version="0.11.6" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.7.0" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <TestProject Include="..\TestProjects\BasicConsole\BasicConsole.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\FennecLabs.Instrumentation\FennecLabs.Instrumentation.csproj" />
    <ProjectReference Include="..\FennecLabs.TestUtilities\FennecLabs.TestUtilities.csproj" />
  </ItemGroup>

  <Import Project="..\FennecLabs.TestUtilities\TestProjectRefs.targets" />

</Project>