<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.8.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\FennecLabs.DotNetCli\FennecLabs.DotNetCli.csproj" />
    <ProjectReference Include="..\..\src\FennecLabs.Contracts\FennecLabs.Contracts.csproj" />
    <ProjectReference Include="..\FennecLabs.TestUtilities\FennecLabs.TestUtilities.csproj" />
  </ItemGroup>

  <ItemGroup>
    <TestProject Include="..\TestProjects\BasicMvcApp\BasicMvcApp.csproj" />
    <TestProject Include="..\TestProjects\PollyAwsMvcApp\PollyAwsMvcApp.csproj" />
    <TestProject Include="..\TestProjects\AnotherWebApp\Web.csproj" />
  </ItemGroup>

  <Import Project="..\FennecLabs.TestUtilities\TestProjectRefs.targets" />

</Project>